# Generated by Django 4.0.5 on 2022-06-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ponds', '0002_alter_pond_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.CharField(max_length=10, verbose_name='Zkratka')),
                ('description', models.CharField(max_length=255, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Jednotka',
                'verbose_name_plural': 'Jednotky',
            },
        ),
        migrations.CreateModel(
            name='PondMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponds.pond', verbose_name='Rybník')),
            ],
        ),
        migrations.CreateModel(
            name='IntegerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_data', models.FloatField(verbose_name='Hodnota')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznánka')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pondmeasurement', verbose_name='Měření')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.unit', verbose_name='Jednotky')),
            ],
            options={
                'verbose_name': 'Data (celé číslo)',
                'verbose_name_plural': 'Data (celá čísla)',
            },
        ),
        migrations.CreateModel(
            name='FloatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float_data', models.FloatField(verbose_name='Hodnota')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznánka')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pondmeasurement', verbose_name='Měření')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.unit', verbose_name='Jednotky')),
            ],
            options={
                'verbose_name': 'Data (desetinné číslo)',
                'verbose_name_plural': 'Data (desetinná čísla)',
            },
        ),
        migrations.CreateModel(
            name='CharData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_data', models.CharField(max_length=50, verbose_name='Hodnota')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznánka')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pondmeasurement', verbose_name='Měření')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.unit', verbose_name='Jednotky')),
            ],
            options={
                'verbose_name': 'Data (řetezec)',
                'verbose_name_plural': 'Data (řetězce)',
            },
        ),
        migrations.CreateModel(
            name='BooleanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean_data', models.BooleanField(default=False, verbose_name='Hodnota')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznánka')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pondmeasurement', verbose_name='Měření')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.unit', verbose_name='Jednotky')),
            ],
            options={
                'verbose_name': 'Data (ano/ne)',
                'verbose_name_plural': 'Data (ano/ne)',
            },
        ),
    ]
