# Generated by Django 4.0.5 on 2022-06-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pondmeasurement',
            options={'verbose_name': 'Měření na rybníku', 'verbose_name_plural': 'Měření na rybnících'},
        ),
    ]
