# Generated by Django 4.0.5 on 2022-06-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_pondmeasurement_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Název parametru')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznámnka')),
            ],
            options={
                'verbose_name': 'Parametr',
                'verbose_name_plural': 'Parametry',
            },
        ),
    ]
