# Generated by Django 4.0.5 on 2022-06-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pondmeasurement',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
