# Generated by Django 4.0.5 on 2022-06-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_pondmeasurement_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pondmeasurement',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka'),
        ),
    ]
