# Generated by Django 4.0.5 on 2022-06-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_pondmeasurement_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='booleandata',
            name='parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.parameter', verbose_name='Parametr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chardata',
            name='parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.parameter', verbose_name='Parametr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floatdata',
            name='parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.parameter', verbose_name='Parametr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integerdata',
            name='parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.parameter', verbose_name='Parametr'),
            preserve_default=False,
        ),
    ]
