# Generated by Django 4.0.5 on 2022-06-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_booleandata_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='datatype',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Float'), (2, 'Integer'), (3, 'Boolean'), (4, 'Char')], default=1, verbose_name='Datový typ'),
            preserve_default=False,
        ),
    ]
