# Generated by Django 4.0.5 on 2022-06-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_parameter_datatype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booleandata',
            old_name='boolean_data',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chardata',
            old_name='char_data',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='floatdata',
            old_name='float_data',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='integerdata',
            old_name='integer_data',
            new_name='value',
        ),
    ]
