# Generated by Django 4.0.5 on 2022-06-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_remove_chardata_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleandata',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='chardata',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='floatdata',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='integerdata',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Název parametru (cs)'),
        ),
    ]
