# Generated by Django 4.0.5 on 2022-06-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_booleandata_note_alter_chardata_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='description',
            new_name='description_cs',
        ),
    ]
