# Generated by Django 4.0.5 on 2022-06-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_unit_description_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='name',
            new_name='name_cs',
        ),
    ]
