# Generated by Django 4.0.5 on 2022-06-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_rename_name_parameter_name_cs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='note',
        ),
        migrations.AddField(
            model_name='parameter',
            name='name_en',
            field=models.CharField(default=1, max_length=50, verbose_name='Název parametru (ens)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='note_cs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznámnka (cs)'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='note_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznámnka (en)'),
        ),
    ]
