# Generated by Django 4.0.5 on 2022-06-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_remove_parameter_note_parameter_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pondmeasurement',
            name='note',
        ),
        migrations.AddField(
            model_name='pondmeasurement',
            name='note_cs',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka (cs)'),
        ),
        migrations.AddField(
            model_name='pondmeasurement',
            name='note_en',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka (en)'),
        ),
    ]
