# Generated by Django 4.0.5 on 2022-06-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_remove_pondmeasurement_note_pondmeasurement_note_cs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name_en',
            field=models.CharField(max_length=50, verbose_name='Název parametru (en)'),
        ),
    ]
