# Generated by Django 4.1 on 2022-08-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0018_alter_parameter_name_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floatdata",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.unit",
                verbose_name="Jednotky",
            ),
        ),
        migrations.AlterField(
            model_name="integerdata",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.unit",
                verbose_name="Jednotky",
            ),
        ),
    ]
