# Generated by Django 4.1.1 on 2022-09-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0019_alter_floatdata_unit_alter_integerdata_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parameter",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="note_en",
        ),
        migrations.RemoveField(
            model_name="pondmeasurement",
            name="note_en",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="description_en",
        ),
    ]
