# Generated by Django 4.1.2 on 2022-10-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0020_remove_parameter_name_en_remove_parameter_note_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pondmeasurement",
            old_name="date",
            new_name="datetime",
        ),
    ]
