# Generated by Django 4.1.2 on 2022-10-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0021_rename_date_pondmeasurement_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pondmeasurement",
            name="datetime",
            field=models.DateTimeField(verbose_name="Datum"),
        ),
    ]
