# Generated by Django 4.1.2 on 2022-10-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0023_fiedlerdata"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fiedlerdata",
            unique_together={("parameter", "measurement")},
        ),
    ]
