# Generated by Django 4.1.2 on 2022-10-05 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0024_alter_fiedlerdata_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameter",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.unit",
                verbose_name="Jednotky",
            ),
        ),
    ]
