# Generated by Django 4.1.2 on 2022-10-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0025_parameter_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fiedlerdata",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="floatdata",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="integerdata",
            name="unit",
        ),
    ]
