# Generated by Django 4.2 on 2023-04-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0027_parametertranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametertranslation",
            name="note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
