# Generated by Django 4.0.5 on 2022-06-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Popis fotografie')),
                ('photo', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Popis fotogalerie'),
        ),
    ]
