# Generated by Django 4.0.5 on 2022-06-14 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_photo_alter_photogallery_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photogallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.photogallery', verbose_name='fotogalerie'),
            preserve_default=False,
        ),
    ]
