# Generated by Django 4.0.5 on 2022-06-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_photo_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Picture',
        ),
    ]
