# Generated by Django 4.0.5 on 2022-06-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_photo_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
