# Generated by Django 4.0.5 on 2022-06-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_photogallery_slug_picture_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photogallery',
            old_name='description',
            new_name='description_cs',
        ),
        migrations.RenameField(
            model_name='photogallery',
            old_name='name',
            new_name='name_cs',
        ),
        migrations.RenameField(
            model_name='photogallery',
            old_name='slug',
            new_name='slug_cs',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='description',
            new_name='description_cs',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='slug',
            new_name='slug_cs',
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='poslední úprava'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Obrázek (soubor)'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='photogallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='webapp.photogallery', verbose_name='fotogalerie'),
        ),
    ]
