# Generated by Django 4.0.5 on 2022-06-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_rename_description_photogallery_description_cs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Popis fotogalerie (cs)'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Název galerie (en)'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='slug_en',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='description_cs',
            field=models.TextField(blank=True, null=True, verbose_name='Popis fotogalerie (cs)'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='name_cs',
            field=models.CharField(max_length=255, verbose_name='Název galerie (cs)'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='description_cs',
            field=models.CharField(max_length=255, verbose_name='Popis fotografie (cs)'),
        ),
    ]
