# Generated by Django 4.0.5 on 2022-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_picture_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='enable',
            field=models.BooleanField(default=False, verbose_name='Zaponout'),
        ),
    ]
