# Generated by Django 4.0.5 on 2022-06-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_photogallery_description_cs_and_more'),
        ('webapp', '0012_picture_slug_en_alter_photogallery_description_en_and_more'),
    ]

    operations = [
    ]
