# Generated by Django 4.0.6 on 2022-07-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_pages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
