# Generated by Django 4.1.1 on 2022-09-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0016_picture_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="content_en",
        ),
        migrations.RemoveField(
            model_name="page",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="page",
            name="slug_en",
        ),
        migrations.RemoveField(
            model_name="photogallery",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="photogallery",
            name="slug_en",
        ),
        migrations.RemoveField(
            model_name="picture",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="picture",
            name="slug_en",
        ),
    ]
