# Generated by Django 4.1.1 on 2022-09-18 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webapp", "0017_remove_page_content_en_remove_page_name_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline_cs",
                    models.CharField(max_length=255, verbose_name="Nadpis"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Poslední úprava"),
                ),
                (
                    "published",
                    models.DateTimeField(auto_now_add=True, verbose_name="Publikováno"),
                ),
                ("text", models.TextField(verbose_name="obsah")),
                ("enable", models.BooleanField(default=False, verbose_name="Zapnout")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photogalleries",
                    models.ManyToManyField(
                        blank=True,
                        to="webapp.photogallery",
                        verbose_name="fotogralerie",
                    ),
                ),
                (
                    "pictures",
                    models.ManyToManyField(
                        blank=True, to="webapp.picture", verbose_name="obrázky"
                    ),
                ),
            ],
        ),
    ]
