# Generated by Django 4.1.1 on 2022-09-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0018_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug_cs",
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
