# Generated by Django 4.2 on 2023-04-16 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0021_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="language",
            options={
                "verbose_name": "Zapnutý jazyk",
                "verbose_name_plural": "Zapnuté jazyky",
            },
        ),
    ]
