# Generated by Django 4.2 on 2023-04-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0022_alter_language_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="lang",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.language",
            ),
        ),
    ]
