# Generated by Django 4.2 on 2023-04-16 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0023_page_lang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="lang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.language"
            ),
        ),
    ]
