# Generated by Django 4.2 on 2023-04-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0024_alter_page_lang"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="content_cs",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="slug_cs",
            new_name="slug",
        ),
        migrations.RemoveField(
            model_name="page",
            name="name_cs",
        ),
        migrations.AddField(
            model_name="page",
            name="name",
            field=models.CharField(default=1, max_length=255, verbose_name="Název"),
            preserve_default=False,
        ),
    ]
