# Generated by Django 4.2 on 2023-04-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0025_rename_content_cs_page_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"verbose_name": "Stránka", "verbose_name_plural": "Stránky"},
        ),
        migrations.AddField(
            model_name="page",
            name="add_to_title",
            field=models.BooleanField(
                default=False, verbose_name="Přidat na titulní stránku"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(verbose_name="Obash (html)"),
        ),
        migrations.AlterField(
            model_name="page",
            name="enable",
            field=models.BooleanField(verbose_name="Zapnuto"),
        ),
        migrations.AlterField(
            model_name="page",
            name="lang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.language",
                verbose_name="Jazyk",
            ),
        ),
    ]
