# Generated by Django 4.2 on 2023-04-16 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0026_alter_page_options_page_add_to_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photogallery",
            old_name="description_cs",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="photogallery",
            old_name="name_cs",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="photogallery",
            old_name="slug_cs",
            new_name="slug",
        ),
    ]
