# Generated by Django 4.2 on 2023-04-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0028_photogalerydescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="photogalerydescription",
            name="slug",
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
