# Generated by Django 4.2 on 2023-04-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0029_photogalerydescription_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photogallery",
            name="description",
        ),
        migrations.RemoveField(
            model_name="photogallery",
            name="name",
        ),
        migrations.AlterField(
            model_name="photogalerydescription",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Popis fotogalerie"
            ),
        ),
        migrations.AlterField(
            model_name="photogalerydescription",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Název galerie"),
        ),
    ]
