# Generated by Django 4.2 on 2023-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0031_picturedescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picturedescription",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Popis obrázku"),
        ),
    ]
