# Generated by Django 4.2 on 2023-04-16 19:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0034_picturedescription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PictureDescription",
        ),
    ]
