# Generated by Django 4.2 on 2023-04-16 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0035_delete_picturedescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="PictureDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Popis obrázku"),
                ),
                ("slug", models.SlugField()),
                (
                    "lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.language",
                        verbose_name="Jazyk",
                    ),
                ),
                (
                    "picture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.picture"
                    ),
                ),
            ],
        ),
    ]
