# Generated by Django 4.2 on 2023-04-16 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0036_picturedescription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="picture",
            name="description_cs",
        ),
        migrations.RemoveField(
            model_name="picture",
            name="slug_cs",
        ),
    ]
