# Generated by Django 4.2 on 2023-04-16 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0037_remove_picture_description_cs_remove_picture_slug_cs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="slug_cs",
        ),
        migrations.CreateModel(
            name="BlogTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("slug", models.SlugField()),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.blog"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.language",
                    ),
                ),
            ],
        ),
    ]
