# Generated by Django 4.2 on 2023-04-17 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0038_remove_blog_slug_cs_blogtranslation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogtranslation",
            old_name="language",
            new_name="lang",
        ),
    ]
