# Generated by Django 4.2 on 2024-05-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0043_alter_blog_youtube"),
    ]

    operations = [
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("data", models.FileField(upload_to="data/%Y/%m/%d/")),
            ],
        ),
    ]
