# Generated by Django 4.0.4 on 2022-05-24 16:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pond_name', models.CharField(max_length=255, verbose_name='jméno rybníku')),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='poloha rybníku (polyogon)')),
            ],
        ),
    ]
