# Generated by Django 4.0.4 on 2022-05-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pond',
            options={'verbose_name': 'Rybník', 'verbose_name_plural': 'Rybníky'},
        ),
    ]
