# Generated by Django 4.0.5 on 2022-06-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0002_alter_pond_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='monitored',
            field=models.BooleanField(default=False, verbose_name='Sledovaný rybník'),
        ),
    ]
