# Generated by Django 4.0.6 on 2022-07-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0003_pond_monitored'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
