# Generated by Django 4.0.6 on 2022-07-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0004_pond_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='qr_code',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
