# Generated by Django 4.0.6 on 2022-07-31 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0006_alter_pond_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pond',
            name='qr_code',
        ),
    ]
