# Generated by Django 4.1 on 2022-08-08 09:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0016_picture_title"),
        ("ponds", "0009_alter_pond_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="pond",
            name="area_m2",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Rozloha rybníku"
            ),
        ),
        migrations.AddField(
            model_name="pond",
            name="main_photogallery",
            field=models.ManyToManyField(to="webapp.picture"),
        ),
        migrations.AddField(
            model_name="pond",
            name="main_text",
            field=models.TextField(blank=True, null=True, verbose_name="Hlavní text"),
        ),
        migrations.AddField(
            model_name="pond",
            name="photogalleries",
            field=models.ManyToManyField(to="webapp.photogallery"),
        ),
        migrations.AlterField(
            model_name="pond",
            name="area",
            field=django.contrib.gis.db.models.fields.PolygonField(
                srid=4326, verbose_name="Poloha rybníku (polyogon)"
            ),
        ),
    ]
