# Generated by Django 4.1 on 2022-08-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0016_picture_title"),
        ("ponds", "0010_pond_area_m2_pond_main_photogallery_pond_main_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pond",
            name="main_photogallery",
            field=models.ManyToManyField(blank=True, to="webapp.picture"),
        ),
        migrations.AlterField(
            model_name="pond",
            name="photogalleries",
            field=models.ManyToManyField(blank=True, to="webapp.photogallery"),
        ),
    ]
