# Generated by Django 4.1 on 2022-08-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ponds", "0012_pond_altitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="pond",
            name="reserve",
            field=models.BooleanField(default=False, verbose_name="Rezerva"),
        ),
    ]
