# Generated by Django 4.1 on 2022-08-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ponds", "0013_pond_reserve"),
    ]

    operations = [
        migrations.AddField(
            model_name="pond",
            name="title_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pond_titles/",
                verbose_name="Titulní obrázek",
            ),
        ),
    ]
