# Generated by Django 4.1 on 2022-08-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ponds", "0014_pond_title_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pond",
            old_name="main_text",
            new_name="main_text_cs",
        ),
    ]
