# Generated by Django 4.1 on 2022-08-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ponds", "0015_rename_main_text_pond_main_text_cs"),
    ]

    operations = [
        migrations.AddField(
            model_name="pond",
            name="main_text_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Hlavní text (en)"
            ),
        ),
        migrations.AlterField(
            model_name="pond",
            name="main_text_cs",
            field=models.TextField(
                blank=True, null=True, verbose_name="Hlavní text (cs)"
            ),
        ),
    ]
