# Generated by Django 4.1.1 on 2022-09-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ponds", "0016_pond_main_text_en_alter_pond_main_text_cs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pond",
            name="main_text_en",
        ),
    ]
