# Generated by Django 4.1.1 on 2022-09-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0018_blog"),
        ("ponds", "0017_remove_pond_main_text_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="pond",
            name="related_blogs",
            field=models.ManyToManyField(blank=True, to="webapp.blog"),
        ),
    ]
