# Generated by Django 4.2 on 2023-04-17 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0039_rename_language_blogtranslation_lang"),
        ("ponds", "0019_pondtexttransations"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PondTextTransations",
            new_name="PondTextTransation",
        ),
    ]
