# Generated by Django 4.2 on 2023-04-17 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ponds", "0021_rename_pondtexttransation_pondtexttranslation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pondtexttranslation",
            old_name="language",
            new_name="lang",
        ),
    ]
