# Generated by Django 4.0.4 on 2022-05-24 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ponds', '0002_alter_pond_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PondVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255, verbose_name='Stručný popis práce')),
                ('dt_start', models.DateTimeField(verbose_name='Začátek')),
                ('dt_end', models.DateTimeField(verbose_name='Konec')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponds.pond', verbose_name='Rybník')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Návštěva rybníku',
                'verbose_name_plural': 'Návštěvy rybníků',
            },
        ),
    ]
