# Generated by Django 4.0.4 on 2022-06-03 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pondvisit',
            name='coworkers',
            field=models.ManyToManyField(related_name='pond_visitor_coworkers', to=settings.AUTH_USER_MODEL, verbose_name='Spolupracovníci'),
        ),
        migrations.AlterField(
            model_name='pondvisit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond_visitor', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel'),
        ),
    ]
