# Generated by Django 4.0.4 on 2022-06-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0002_alter_pond_options'),
        ('cal', '0002_pondvisit_coworkers_alter_pondvisit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pondvisit',
            name='pond',
        ),
        migrations.AddField(
            model_name='pondvisit',
            name='pond',
            field=models.ManyToManyField(to='ponds.pond', verbose_name='Rybník'),
        ),
    ]
