# Generated by Django 4.0.4 on 2022-06-03 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0003_remove_pondvisit_pond_pondvisit_pond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pondvisit',
            name='coworkers',
            field=models.ManyToManyField(blank=True, related_name='pond_visitor_coworkers', to=settings.AUTH_USER_MODEL, verbose_name='Spolupracovníci'),
        ),
    ]
