# Generated by Django 4.0.4 on 2022-06-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_alter_pondvisit_coworkers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pondvisit',
            old_name='pond',
            new_name='ponds',
        ),
    ]
