# Generated by Django 4.0.5 on 2022-06-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0002_alter_pond_options'),
        ('cal', '0005_rename_pond_pondvisit_ponds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pondvisit',
            name='ponds',
            field=models.ManyToManyField(to='ponds.pond', verbose_name='Rybníky'),
        ),
    ]
